# -*- coding: utf-8 -*-
"""train_yolo11n_mixed_22000_checked_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GJ3McVmbVMQQMa9J5m8iK3wEXvYrJG1A

# Train PPE Dataset with YOLO11n

Colab에 아래 zip 파일을 업로드한 뒤 위에서부터 실행하세요.

```text
mixed_22000_plus_checked4000_train_valid_colab.zip
```

클래스는 `head`, `helmet`, `vest` 3개입니다.
"""

!nvidia-smi
!pip install -q -U ultralytics

# Google Drive를 Colab에 연결합니다.
from google.colab import drive  # Google Drive를 Colab에서 사용하기 위한 모듈입니다.

drive.mount("/content/drive")  # Google Drive를 /content/drive 경로에 연결합니다.

from pathlib import Path
import shutil
import zipfile

ZIP_PATH = Path('/content/drive/MyDrive/mixed_22000_plus_checked4000_train_valid_colab.zip')
WORK_DIR = Path('/content/ppe_yolo11n_dataset')

if not ZIP_PATH.exists():
    candidates = sorted(Path('/content').glob('*mixed*22000*checked4000*.zip'))
    if not candidates:
        candidates = sorted(Path('/content').glob('*mixed*.zip'))
    if candidates:
        ZIP_PATH = candidates[0]
    else:
        raise FileNotFoundError('Upload mixed_22000_plus_checked4000_train_valid_colab.zip to /content first')

if WORK_DIR.exists():
    shutil.rmtree(WORK_DIR)
WORK_DIR.mkdir(parents=True, exist_ok=True)

with zipfile.ZipFile(ZIP_PATH, 'r') as zf:
    zf.extractall(WORK_DIR)

yaml_files = sorted(WORK_DIR.rglob('data.yaml'))
if not yaml_files:
    raise FileNotFoundError('data.yaml not found inside zip')

DATA_YAML = yaml_files[0]
DATA_ROOT = DATA_YAML.parent

print('ZIP_PATH =', ZIP_PATH)
print('DATA_ROOT =', DATA_ROOT)
print('DATA_YAML =', DATA_YAML)
!find /content/ppe_yolo11n_dataset -maxdepth 4 -type d | sort | head -40

DATA_YAML.write_text(
    f'path: {DATA_ROOT.as_posix()}\n'
    'train: train/images\n'
    'val: valid/images\n'
    '\n'
    'nc: 3\n'
    "names: ['head', 'helmet', 'vest']\n",
    encoding='utf-8',
)
print(DATA_YAML.read_text())

train_images = list((DATA_ROOT / 'train' / 'images').glob('*'))
valid_images = list((DATA_ROOT / 'valid' / 'images').glob('*'))
train_labels = list((DATA_ROOT / 'train' / 'labels').glob('*.txt'))
valid_labels = list((DATA_ROOT / 'valid' / 'labels').glob('*.txt'))

print('train images:', len(train_images))
print('train labels:', len(train_labels))
print('valid images:', len(valid_images))
print('valid labels:', len(valid_labels))

from ultralytics import YOLO

EPOCHS = 20
IMGSZ = 416
BATCH = -1
RUN_NAME = 'PPE_yolo11n_mixed_22000_checked4000'

model = YOLO('yolo11n.pt')
results = model.train(
    data=str(DATA_YAML),
    imgsz=IMGSZ,
    epochs=EPOCHS,
    batch=BATCH,
    patience=20,
    project='/content/runs/detect',
    name=RUN_NAME,
    exist_ok=True,
)

from pathlib import Path

BEST_PT = Path('/content/runs/detect') / RUN_NAME / 'weights' / 'best.pt'
LAST_PT = Path('/content/runs/detect') / RUN_NAME / 'weights' / 'last.pt'

print('BEST_PT =', BEST_PT)
print('LAST_PT =', LAST_PT)
print('best exists:', BEST_PT.exists())
print('last exists:', LAST_PT.exists())

from google.colab import files

if not BEST_PT.exists():
    raise FileNotFoundError('best.pt not found')

files.download(str(BEST_PT))

from pathlib import Path
from google.colab import files
import shutil

RUN_DIR = Path('/content/runs/detect') / RUN_NAME
DOWNLOAD_DIR = Path('/content/yolo11n_training_outputs')
ZIP_OUT = Path('/content/yolo11n_training_outputs.zip')

if DOWNLOAD_DIR.exists():
    shutil.rmtree(DOWNLOAD_DIR)
DOWNLOAD_DIR.mkdir(parents=True, exist_ok=True)

# 대표 결과 파일들
wanted_files = [
    'results.csv',
    'results.png',
    'confusion_matrix.png',
    'confusion_matrix_normalized.png',
    'F1_curve.png',
    'P_curve.png',
    'R_curve.png',
    'PR_curve.png',
    'labels.jpg',
    'labels_correlogram.jpg',
    'train_batch0.jpg',
    'train_batch1.jpg',
    'train_batch2.jpg',
    'val_batch0_labels.jpg',
    'val_batch0_pred.jpg',
    'val_batch1_labels.jpg',
    'val_batch1_pred.jpg',
    'val_batch2_labels.jpg',
    'val_batch2_pred.jpg',
]

for name in wanted_files:
    src = RUN_DIR / name
    if src.exists():
        shutil.copy2(src, DOWNLOAD_DIR / name)

# weights도 같이 저장하고 싶으면 포함
weights_dir = RUN_DIR / 'weights'
if weights_dir.exists():
    shutil.copytree(weights_dir, DOWNLOAD_DIR / 'weights', dirs_exist_ok=True)

# args.yaml 등 설정 파일도 포함
for extra in ['args.yaml']:
    src = RUN_DIR / extra
    if src.exists():
        shutil.copy2(src, DOWNLOAD_DIR / extra)

shutil.make_archive(str(ZIP_OUT.with_suffix('')), 'zip', DOWNLOAD_DIR)

print('RUN_DIR =', RUN_DIR)
print('ZIP_OUT =', ZIP_OUT)
files.download(str(ZIP_OUT))

# Optional: Raspberry Pi 배포용 ONNX export
# 필요할 때만 실행하세요.
export_model = YOLO(str(BEST_PT))
onnx_path = export_model.export(format='onnx', imgsz=IMGSZ, simplify=True)
print('ONNX =', onnx_path)
files.download(str(onnx_path))